AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 122

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/Void:
  Enabled: false  

Style/RedundantArgument:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 11        

Metrics/PerceivedComplexity:
  Max: 12 